spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cartao_db
    username: postgres
    password: "%%postgres"
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true

jwt:
  secret: sua-chave-64-caracteres-aqui
  expiration: 3600000 # 1 hora em ms 